### ISSUE TITLE
Keyboard capture issue

### ISSUE THREAD

**Issue by mathuin** [dsonbill/kOSPropMonitor#3]
When I install this mod, keys are not captured correctly.

I put a kOS-enabled craft on the launch pad, select the kOS part, click 'open terminal', and type this line: 
 `switch to 0. runpath("hellolaunch.ks").`

What I expected to happen was for the craft to launch in accordance with the script.  What actually happened was a transition to IVA mode and back due to the `c` characters in that line, plus the enabling of my atmospheric autopilot due to the `p` character.

Removing this mod makes the problem go away.

If there's anything I can do to help, please let me know!

**Comment by dsonbill** [comment]
Your resolution makes perfect sense. Full steam ahead.

On a more serious note, I'll try to fix the control locks and anything else I forgot to do to this thing soon.

**Comment by mathuin** [comment]
The mod "ClickThrough Blocker" by linuxgurugamer should address this issue, but I am insufficiently familiar with C# to submit a PR to this repo to support this mod.  https://github.com/linuxgurugamer/ClickThroughBlocker is the repo for that mod.

**Comment by dsonbill** [comment]
I'm not sure what caused this, but it doesn't seem to be an issue any more. If anyone has this problem, just let me know and I'll re-open it and try to hunt down the cause.
