### ISSUE TITLE
Bug with KOS 1.3.2 in mfd input char don't work

### ISSUE THREAD

**Issue by Massetstephane** [dsonbill/kOSPropMonitor#6]
hi !
There a bug in mfd terminal with the plugins kOSPropMonitor. (using rasterprop mfd)
button work, but it's impossible to write something on the screen.
with the last KOS version 1.3.2
the error: 
Exception:MissingMethodException:void
Kos.screen.TermWindows.ProcessOneInputChar(char,kos.UserIO.TelnetSingletonServer,bool).

the log file 
[KSP.log](https://github.com/dsonbill/kOSPropMonitor/files/5871865/KSP.log)

from : JonnyOThan 
This is an incompatibility between kOSPropMonitor and the new version of kOS. KPM is calling ProcessOneInputChar via reflection, but the signature of that function changed in KOS 1.3 (added an extra bool parameter).

**Comment by Dunbaratu** [comment]
The odd thing is that even though an extra bool parameter was added, it was given a default.  But maybe the reflection call was looking for the exact signature rather than one that would be compatible with defaults added like a compile-time binding would do.
