### ISSUE TITLE
Message : kPM: Ship Reconfiguring 

### ISSUE THREAD

**Issue by Massetstephane** [dsonbill/kOSPropMonitor#7]
hi ! 
I have a new problem 
I have nothing to change in KOS or KPM, but when I'm outside the ship this message : 

_[LOG 21:34:29.548] Camera alt: 8.98258, craft alt: 8.8687801361084
[LOG 21:34:29.548] kPM: Ship Reconfiguring_

appears looped in the KSP debug console.
I didn't see it right away because I didn't have a lot of Mod to install and I didn't fix the console.
my mod : 
![image](https://user-images.githubusercontent.com/70191880/110236305-58846d00-7f35-11eb-9e74-f2cffdab974b.png)

log file 
[KSP.log](https://github.com/dsonbill/kOSPropMonitor/files/6096922/KSP.log)

steph.

**Comment by dsonbill** [comment]
Fixed on latest release, thank you for the report
